// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: celestia/minfee/v1/genesis.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the minfee module's genesis state.
type GenesisState struct {
	NetworkMinGasPrice cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=network_min_gas_price,json=networkMinGasPrice,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"network_min_gas_price"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_40506204178306cf, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GenesisState)(nil), "celestia.minfee.v1.GenesisState")
}

func init() { proto.RegisterFile("celestia/minfee/v1/genesis.proto", fileDescriptor_40506204178306cf) }

var fileDescriptor_40506204178306cf = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x37, 0x17, 0xc1, 0xc5, 0xd3, 0xa2, 0xa0, 0x15, 0xd2, 0xe2, 0xc9, 0x4b, 0x13, 0x56,
	0xdf, 0xa0, 0x14, 0x7a, 0xa9, 0x20, 0x7a, 0xf3, 0xb2, 0xa4, 0xe9, 0x98, 0x86, 0x9a, 0xcc, 0xb2,
	0x19, 0xab, 0x7d, 0x0b, 0x1f, 0xc6, 0x87, 0xe8, 0xb1, 0x78, 0x12, 0x0f, 0x45, 0x76, 0x5f, 0x44,
	0xb6, 0xe9, 0x7a, 0xfb, 0x87, 0xff, 0x9f, 0x6f, 0xf8, 0x27, 0x1d, 0x68, 0x78, 0x81, 0x40, 0x56,
	0x49, 0x67, 0xfd, 0x33, 0x80, 0x5c, 0xe5, 0xd2, 0x80, 0x87, 0x60, 0x83, 0x28, 0x2b, 0x24, 0xcc,
	0xb2, 0x2e, 0x21, 0x62, 0x42, 0xac, 0xf2, 0xde, 0xa9, 0x41, 0x83, 0x7b, 0x5b, 0xb6, 0x2a, 0x26,
	0x7b, 0x17, 0x1a, 0x83, 0xc3, 0x50, 0x44, 0x23, 0x0e, 0xd1, 0xba, 0xa2, 0xf4, 0x64, 0x12, 0xa9,
	0x8f, 0xa4, 0x08, 0xb2, 0x79, 0x7a, 0xe6, 0x81, 0xde, 0xb0, 0x5a, 0x16, 0xce, 0xfa, 0xc2, 0xa8,
	0x76, 0xcb, 0x6a, 0x38, 0x67, 0x03, 0x76, 0x7d, 0x3c, 0xca, 0x37, 0xbb, 0x7e, 0xf2, 0xb3, 0xeb,
	0x5f, 0x46, 0x48, 0x98, 0x2f, 0x85, 0x45, 0xe9, 0x14, 0x2d, 0xc4, 0x14, 0x8c, 0xd2, 0xeb, 0x31,
	0xe8, 0xaf, 0xcf, 0x61, 0x7a, 0xb8, 0x31, 0x06, 0xfd, 0x90, 0x1d, 0x78, 0x77, 0xd6, 0x4f, 0x54,
	0xb8, 0x6f, 0x61, 0xa3, 0xe9, 0xa6, 0xe6, 0x6c, 0x5b, 0x73, 0xf6, 0x5b, 0x73, 0xf6, 0xd1, 0xf0,
	0x64, 0xdb, 0xf0, 0xe4, 0xbb, 0xe1, 0xc9, 0xd3, 0x8d, 0xb1, 0xb4, 0x78, 0x9d, 0x09, 0x8d, 0x4e,
	0x76, 0xfd, 0xb0, 0x32, 0xff, 0x7a, 0xa8, 0xca, 0x52, 0xbe, 0x77, 0x3f, 0xa1, 0x75, 0x09, 0x61,
	0x76, 0xb4, 0xaf, 0x72, 0xfb, 0x17, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x35, 0x9f, 0xe1, 0x33, 0x01,
	0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.NetworkMinGasPrice.Size()
		i -= size
		if _, err := m.NetworkMinGasPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.NetworkMinGasPrice.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkMinGasPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NetworkMinGasPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
