name: Test Multiplexer

on:
  workflow_dispatch:
  pull_request:

jobs:
  test-multiplexer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Nova repository
        uses: actions/checkout@v4
        with:
          repository: 01builders/nova
          path: nova

      - name: Checkout Celestia-App repository
        uses: actions/checkout@v4
        with:
          repository: 01builders/celestia-app
          ref: cian/add-basic-nova-e2e # TODO: change before merging to be the feature branch.
          path: celestia-app

      - name: Download latest Celestia-App Linux tarball
        run: curl -Lo nova/appd/celestia-app_Linux_x86_64.tar.gz https://github.com/celestiaorg/celestia-app/releases/download/v3.4.0/celestia-app_Linux_x86_64.tar.gz

      - name: Update go.mod in Celestia-App to use local Nova module
        run: |
          cd celestia-app
          go mod edit -replace github.com/01builders/nova=../nova
          go mod tidy

      - name: Install Celestia-App
        run: |
          cd celestia-app
          make install
          mv build/celestia-appd /usr/local/bin/celestia-appd

      - name: Verify Binary Installation
        run: which celestia-appd && celestia-appd version

      - name: Run tests in Celestia-App
        run: |
          cd celestia-app
          make test-multi-plexer
