name: test-multiplexer
on:
  workflow_dispatch:
  pull_request:

jobs:
  test-multiplexer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Celestia-App repository
        uses: actions/checkout@v4

      - name: Download v3 Celestia Binary
        run: curl -L -o internal/embedding/celestia-app_Linux_x86_64.tar.gz https://github.com/celestiaorg/celestia-app/releases/download/v3.4.0/celestia-app_Linux_x86_64.tar.gz

      - name: Build Celestia-App
        run: |
          make build
          chmod +x build/celestia-appd
          mv build/celestia-appd /usr/local/bin/celestia-appd

      - name: Verify Binary Installation
        run: |
          which celestia-appd
          celestia-appd version

      - name: Run Multiplexer tests
        run: make test-multi-plexer
